spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: password
    dataSourceClassName: org.postgresql.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  profiles:
    active: development
  main:
    banner-mode: off

server:
  port: 9292